name: Build Windows EXE (PyInstaller)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          python -m pip show pyinstaller

      - name: Build EXE
        run: |
          python -m PyInstaller --noconfirm --clean --onefile --windowed `
            --name "ImgOps" `
            --icon "icon.ico" `
            --add-data "images;images" `
            --add-data "app.py;." `
            --add-data "app2.py;." `
            --add-data "pic.py;." `
            --add-data "gimp.py;." `
            app2.py

      - uses: actions/upload-artifact@v4
        with:
          name: ImgOps-windows
          path: dist/ImgOps.exe
